[project]
name = 'countess-minimap2'
dynamic = ["version"]
readme = "README.md"
authors = [
    { name = "Nick Moore", email="nick@zoic.org" },
]
maintainers = [
    { name = "Nick Moore", email="nick@zoic.org" },
]
description = "Sequence Alignment Plugin for CountESS, based in Minimap2"
requires-python = ">=3.10"
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
]
dependencies = [
    "countess>=0.1.21",
    "mappy~=2.28",
]
license = "BSD-3-Clause"

[project.urls]
Homepage = "https://github.com/CountESS-Project/countess-minimap2"
Repository = "https://github.com/CountESS-Project/countess-minimap2.git"

[project.optional-dependencies]
dev = [
    "countess[dev]>=0.1.21",
    "build~=1.2.2",
    "twine~=6.1.0",
]

[project.entry-points.countess_plugins]
minimap2 = "countess_minimap2:MiniMap2Plugin"

[tool.setuptools.dynamic]
version = { attr = "countess_minimap2.VERSION" }
readme = { file = "README.md", content-type="text/markdown" }

[tool.pylint]
disable = [
    "c-extension-no-member",
    "fixme",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-return",
    "too-many-ancestors",
]
max-line-length = 120

[tool.black]
line-length = 120
